### ISSUE TITLE
_imgt_check fails for mouse TRA contigs

### ISSUE THREAD

**Issue by ssnn-airr** [immcantation/changeo#198]
**[Original report](https://bitbucket.org/kleinstein/changeo/issues/198) by zewen.tuong (Bitbucket: [zewen.tuong](https://bitbucket.org/zewen.tuong), ).**

----------------------------------------

Hi, thanks for all the great tools - i’m noticing an issue when running MakeDb.py on mouse TCR data where TRA contigs are flagged as invalid at the  `_imgt_check` step.

‌

in my test case, the second sequence was the first TRA contig

```
with open(aligner_file, 'r') as f:
    parse_iter = parser(f, seq_dict, references, regions=regions, asis_calls=asis_calls, infer_junction=infer_junction)
    germ_iter = (addGermline(x, references, amino_acid=amino_acid) for x in parse_iter)
    count = 0
    for record in germ_iter:
        count += 1
        if count == 2:
            print(record.v_call)
            print(record.j_call)
            print(record.functional)
            print(record.sequence_imgt)
            print(record.junction)
            print(_imgt_check(record))
        if count == 2:
            break
```

and the outputs are:  

```
TRAV3-3*01
TRAJ23*01
True
GGCGAGCAGGTGGAGCAGCGCCCT...CCTCACCTGAGTGTCCGGGAGGGAGACAGTGCCGTTATCACCTGCACCTACACAGACCCTAAC..................AGTTATTACTTCTTCTGGTACAAGCAAGAGCCGGGGGCAAGTCTTCAGTTGCTTATGAAGGTTTTCTCAAGT.........ACGGAAATAAACGAAGGA...............CAAGGATTCACTGTCCTACTGAACAAGAAAGAC...AAACGACTCTCTCTGAACCTCACAGCTGCCCATCCTGGGGACTCAGCCGCGTACTTCTGCGCAGTCAGTGCATTTGGCTATAACCAGGGGAAGCTTATCTTTGGACAGGGAACCAAGTTATCTATCAAGCCCA
TGCGCAGTCAGTGCATTTGGCTATAACCAGGGGAAGCTTATCTTT
False
```

‌

`TGCGCAGTCAGTGCATTTGGCTATAACCAGGGGAAGCTTATCTTT` is the junction and is what’s reported in the igblast.fmt7 output 

‌

but within `_imgt_check`, the output from is `record.sequence_imgt[x:y]`:

```
TACTTCTGCGCAGTCAGTGCATTTGGCTATAACCAGGGGAAGCTT
```

‌

so `check = (rec.junction == rec.sequence_imgt[x:y])` fails.

‌

Any potential ideas on what could be going on?

‌

**Comment by NathaneilKnight** [comment]
@ssnn-airr Any update on this? I'm working on chicken BCR analysis, and all the igBlast results fail in the MakeDB.py step.
···
ERROR> Junction does not match the sequence starting at position 310 in the IMGT numbered V(D)J sequence.
···
Is there any other way to resolve this in addition to manually filtering？

**Comment by ssnn-airr** [comment]
This is still the workaround.
